using System.IO;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

[InitializeOnLoad]
public static class Toon2DSceneBuilder
{
    private const string ScenePath = "Assets/Scenes/SampleScene.unity";
    private const string MaterialFolder = "Assets/Rendering/Toon2D/Materials/Demo";
    private const string AutoBuildMarkerPath = "Assets/Rendering/Toon2D/Editor/Generated/.toon_scene_built";

    static Toon2DSceneBuilder()
    {
        EditorApplication.delayCall += AutoBuildOnce;
    }

    private static void AutoBuildOnce()
    {
        if (EditorApplication.isPlayingOrWillChangePlaymode || File.Exists(AutoBuildMarkerPath))
        {
            return;
        }

        RebuildDemoScene();
        File.WriteAllText(AutoBuildMarkerPath, "Generated by Toon2DSceneBuilder.\n");
        AssetDatabase.ImportAsset(AutoBuildMarkerPath);
    }

    [MenuItem("Tools/Toon 2D/Rebuild Demo Scene")]
    public static void RebuildDemoScene()
    {
        EnsureFolder(MaterialFolder);
        EnsureFolder("Assets/Rendering/Toon2D/Editor/Generated");

        var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);
        scene.name = "SampleScene";

        RenderSettings.ambientMode = UnityEngine.Rendering.AmbientMode.Flat;
        RenderSettings.ambientLight = new Color(0.33f, 0.38f, 0.46f);
        RenderSettings.skybox = CreateSkyboxMaterial();
        RenderSettings.fog = false;

        var red = CreateToonMaterial("Toon_Red", new Color(0.96f, 0.28f, 0.22f), new Color(0.34f, 0.08f, 0.08f), 0.0085f);
        var teal = CreateToonMaterial("Toon_Teal", new Color(0.10f, 0.76f, 0.70f), new Color(0.03f, 0.25f, 0.28f), 0.0075f);
        var yellow = CreateToonMaterial("Toon_Yellow", new Color(1.0f, 0.78f, 0.22f), new Color(0.42f, 0.24f, 0.04f), 0.008f);
        var violet = CreateToonMaterial("Toon_Violet", new Color(0.56f, 0.36f, 0.92f), new Color(0.18f, 0.10f, 0.32f), 0.0075f);
        var terrain = CreateToonMaterial("Toon_Terrain", new Color(0.48f, 0.74f, 0.38f), new Color(0.18f, 0.34f, 0.22f), 0.004f);

        CreatePrimitive("Toon Cube", PrimitiveType.Cube, new Vector3(-2.3f, 0.65f, 0f), new Vector3(1.3f, 1.3f, 1.3f), red, new Vector3(0f, 28f, 0f));
        CreatePrimitive("Toon Sphere", PrimitiveType.Sphere, new Vector3(-0.35f, 0.8f, -0.15f), new Vector3(1.55f, 1.55f, 1.55f), teal, Vector3.zero);
        CreatePrimitive("Toon Capsule", PrimitiveType.Capsule, new Vector3(1.75f, 1.05f, 0.1f), new Vector3(1.0f, 1.25f, 1.0f), yellow, new Vector3(0f, -18f, 0f));
        CreatePrimitive("Toon Cylinder", PrimitiveType.Cylinder, new Vector3(3.15f, 0.55f, -0.35f), new Vector3(0.9f, 0.55f, 0.9f), violet, new Vector3(0f, 0f, 0f));
        CreatePrimitive("Toon Terrain Ground", PrimitiveType.Cube, new Vector3(0.35f, -0.12f, 0.1f), new Vector3(9.8f, 0.2f, 4.6f), terrain, Vector3.zero);
        CreatePrimitive("Terrain Ridge Left", PrimitiveType.Cube, new Vector3(-3.15f, 0.03f, 1.1f), new Vector3(2.35f, 0.26f, 0.72f), terrain, new Vector3(0f, 20f, 0f));
        CreatePrimitive("Terrain Ridge Back", PrimitiveType.Cube, new Vector3(2.55f, 0.02f, 1.2f), new Vector3(2.8f, 0.22f, 0.62f), terrain, new Vector3(0f, -15f, 0f));
        CreatePrimitive("Terrain Slope Patch", PrimitiveType.Cube, new Vector3(0.55f, 0.01f, -1.35f), new Vector3(3.1f, 0.18f, 0.7f), terrain, new Vector3(10f, 0f, -6f));

        CreateLight();
        CreateCamera();

        EditorSceneManager.SaveScene(scene, ScenePath);
        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();
    }

    private static Material CreateToonMaterial(string name, Color baseColor, Color shadowColor, float outlineWidth)
    {
        var shader = Shader.Find("Custom/ToonRampOutline");
        if (shader == null)
        {
            Debug.LogError("Custom/ToonRampOutline shader was not found.");
            return null;
        }

        var path = $"{MaterialFolder}/{name}.mat";
        var material = AssetDatabase.LoadAssetAtPath<Material>(path);
        if (material == null)
        {
            material = new Material(shader);
            AssetDatabase.CreateAsset(material, path);
        }

        material.shader = shader;
        material.SetTexture("_MainTex", null);
        material.SetColor("_Color", baseColor);
        material.SetColor("_ShadowColor", shadowColor);
        material.SetColor("_HighlightColor", Color.white);
        material.SetFloat("_RampSteps", 3f);
        material.SetFloat("_SpecularSize", 0.72f);
        material.SetFloat("_SpecularStrength", 0.28f);
        material.SetColor("_OutlineColor", new Color(0.018f, 0.017f, 0.02f, 1f));
        material.SetFloat("_OutlineWidth", outlineWidth);
        EditorUtility.SetDirty(material);
        return material;
    }

    private static Material CreateSkyboxMaterial()
    {
        var shader = Shader.Find("Custom/AnimatedSkybox");
        if (shader == null)
        {
            Debug.LogError("Custom/AnimatedSkybox shader was not found.");
            return null;
        }

        var path = $"{MaterialFolder}/Animated_Skybox.mat";
        var material = AssetDatabase.LoadAssetAtPath<Material>(path);
        if (material == null)
        {
            material = new Material(shader);
            AssetDatabase.CreateAsset(material, path);
        }

        material.shader = shader;
        material.SetColor("_TopColor", new Color(0.18f, 0.5f, 0.95f));
        material.SetColor("_HorizonColor", new Color(0.48f, 0.75f, 1f));
        material.SetColor("_GroundColor", new Color(0.38f, 0.64f, 0.9f));
        material.SetFloat("_BandStrength", 0.02f);
        EditorUtility.SetDirty(material);
        return material;
    }

    private static void CreatePrimitive(string name, PrimitiveType type, Vector3 position, Vector3 scale, Material material, Vector3 eulerAngles)
    {
        var obj = GameObject.CreatePrimitive(type);
        obj.name = name;
        obj.transform.position = position;
        obj.transform.localScale = scale;
        obj.transform.rotation = Quaternion.Euler(eulerAngles);

        var renderer = obj.GetComponent<Renderer>();
        if (renderer != null && material != null)
        {
            renderer.sharedMaterial = material;
        }
    }

    private static void CreateLight()
    {
        var lightObject = new GameObject("Key Toon Light");
        lightObject.transform.rotation = Quaternion.Euler(42f, -34f, 0f);

        var light = lightObject.AddComponent<Light>();
        light.type = LightType.Directional;
        light.color = new Color(1f, 0.94f, 0.82f);
        light.intensity = 1.35f;
        light.shadows = LightShadows.Soft;
        light.shadowStrength = 0.85f;
    }

    private static void CreateCamera()
    {
        var cameraObject = new GameObject("Main Camera");
        cameraObject.tag = "MainCamera";
        cameraObject.transform.position = new Vector3(0.45f, 4.1f, -6.7f);
        cameraObject.transform.rotation = Quaternion.Euler(31f, 0f, 0f);

        var camera = cameraObject.AddComponent<Camera>();
        camera.clearFlags = CameraClearFlags.Skybox;
        camera.backgroundColor = new Color(0.58f, 0.68f, 0.80f);
        camera.orthographic = true;
        camera.orthographicSize = 3.0f;
        camera.allowHDR = false;
        camera.allowMSAA = true;
        camera.depthTextureMode = DepthTextureMode.DepthNormals;

        var outline = cameraObject.AddComponent<ToonScreenSpaceOutline>();
        outline.outlineColor = new Color(0.018f, 0.017f, 0.02f, 1f);
        outline.thickness = 1f;
        outline.depthThreshold = 0.012f;
        outline.normalThreshold = 0.18f;
        outline.strength = 0.85f;

        var pixelate = cameraObject.AddComponent<ToonPixelatePostProcess>();
        pixelate.referenceHeight = 300;
        pixelate.colorSteps = 40f;
        pixelate.ditherStrength = 0.012f;

        cameraObject.AddComponent<AudioListener>();
    }

    private static void EnsureFolder(string path)
    {
        if (AssetDatabase.IsValidFolder(path))
        {
            return;
        }

        var parent = Path.GetDirectoryName(path)?.Replace("\\", "/");
        var folderName = Path.GetFileName(path);
        if (!string.IsNullOrEmpty(parent) && !AssetDatabase.IsValidFolder(parent))
        {
            EnsureFolder(parent);
        }

        AssetDatabase.CreateFolder(parent, folderName);
    }
}
